# For renames, change the name and add the old label name as value to from_label key.
# Push and wait for changes to be propagated to the GitHub side. When propagated, you can safely comment out it.
# Also remember to keep this in-sync with any changes you made through the UI or API to avoid chaos.
# Docs: https://github.com/crazy-max/ghaction-github-labeler#usage
- name: ":arrow_heading_down: pull"
  description: "PRs with this label are usualy automated PRs from Pull."
  color: "ededed"
- name: "Updated by Dependabot"
  description: "Pull requests from Dependabot regarding dependency upgrades for automated triages"
  color: "C3FB57"
- name: "dependencies"
  description: "Changes to an dependency file/lockfile (e.g. npmjs/yarnpkg lockfile, Pipfile, etc.)"
  color: "2E0D86"
- name: "ci/github-actions"
  description: "Changes to the workflow files for GitHub Actions"
  color: "1d76db"
- name: "packages/docker-base-images"
  description: "Changes to the base image, including upgrades made by Dependabot."
  color: "e96695"
- name: "packages/nodejs-npm"
  description: "Dependency upgrades for Node.js packages on different Yarn workspaces of the repo"
  color: "38E1F1"
- name: "Ready to Ship"
  description: "PRs with this label are automagically merged by the PR Merger GitHub workflow once approved."
  color: "0E8A16"
- name: "Blocked from Merging"
  description: "Blocks PRs from ever merging without removal of this label. Triggers WIP-styled blocks."
  color: "D93F0B"
- name: "automation/mergify-approve-rule"
  description: "Automation label for either Mergify and/or your bot account to approve PRs."
  color: "C66003"
- name: "request-forms:new-entries"
  description: "Used in an issue template (issue form for GitHub users) to add an new entry to the list."
  color: "82C065"
- name: "request-forms:update-existing-entries"
  description: "Used in an issue template (issue form for GitHub users) to update existing entry to the list."
  color: "fe1153"
- name: "request-forms:burninate-entries"
  description: "Used in an issue template (issue form for GitHub users) to disable/burninate entires from the list."
  color: "323033"
- name: "request-forms:enable-redirection"
  description: "Used in an issue template (issue form for GitHub users) to enable entry redirection."
  color: "323033"
- name: "request-forms:disable-redirection"
  description: "Used in an issue template (issue form for GitHub users) to disable entry redirection."
  color: "323033"
- name: "workspace:@rtapp-verify/entry-manifests"
  description: "Issues and PRs for the lists directory, also known as @rtapp-verify/entry-manifests package"
  color: "87ed39"
