name: "PR Reviews CI"

on: [pull_request]

jobs:
  automated-reviews:
    name: Automated PR Reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Danger JS
        uses: danger/danger-js@10.6.6
        env:
          DANGER_GITHUB_API_TOKEN: ${{secrets.GH_SERVICE_ACCOUNT_API_KEY}}